name: Sync to Hugging Face hub
on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git config --global user.email "bot@example.com"
          git config --global user.name "Bot"
          git init
          git add .
          git commit -m "Deploy to HF Space"
          git push --force https://DarshanRevankar:$HF_TOKEN@huggingface.co/spaces/DarshanRevankar/newsAI master:main
